apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DockerHerotozero
  description: Repo to master Docker from zero to hero.
  annotations:
    github.com/project-slug: chaitu2201/Docker-course
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: Service
  owner: DevOpsPlatform
  lifecycle: experimental
